export const companionData = {
  "Rat": {
    "Rat": [
      "Make no mistake about it, this animal can only be master or slave. He can be master of the art of trickery and of prudence, instigator of plots, puller of strings behind the political scene or a great militarist and emperor of strategy. That is unless, from his earliest childhood, this Rat/Rat turns out to be a frentic individualist, rejecting dogmas and principles, constraints and proprieties, perpetually on the hunt for food and lodging with the aggressiveness to be expected of such a rodent.",
      "In his other aspect, as a slave, he will be in a state of permanent conflict with himself, having chosen the servitude of the 'domestic rat', which, despite its apparent advantages, will always be at war with his instinctive need to be independent and self-supporting. As a slave, he has to renounce his desire to bewitch and fascinate others. This Rat/Rat will not frighten anyone but himself."
    ],
    "Ox": ["Here the Companion is a striking example of a pseudo guardian angel. The aggressions of the Rat are tempered by the tranquil force of the Ox. The Rat explores in depth, the Ox on the surface. Both being creators, it is the Ox who sometimes, by butting with his horns, will force the Rat to leave his underground passages, jostling him from his fortifications. A love of liberty, the Buffalo will rarely be sidetracked. If the Rat symbolizes perpetual movement, the other symbolizes slowness; and if Ox dreams of virgin territory, the Rat dreams of impenetrable universes. The Rat/Ox will be realistic, prudent and will know how to reinforce his success."],
    "Tiger": ["When a rodent is coupled with a carnivorous animal, the voyage will not be very peaceful; count on the Tiger, he will see to it that you do not fall asleep on your laurels! The hunt is his domain, the jungle his universe; the way will be strewn with traps and nothing will escape his vigilance. As a sentinel, he is unsurpassed. However, do not forget that the Tiger is a noble lord, who will expect to be first. In roaming various territories, he will appropriate them, and the individualistic Rat nature will respond with a violent revolt, which may result in your being emotionally torn. Do not despair. The Tiger is also a symbol of moderation. He is an excellent guide, in every sense of the term, and the Rat, at times a usurper himself, will gain in tolerance and loyalty."],
    "Rabbit": ["This is a curious mixture, to say the least. Are you not these hereditary enemies 'condemned' to travel the same route? But do not be fooled, for this may be the best way to accomplish the voyage. An apprehensive Rat coupled with the eternally stalking Rabbit will not be easily deceived. Suspicious, both adaptable and aggressive, he will be ready to protect himself from predators and to go to any lengths to secure his comfort and vested interests. Also, the influence of the Rabbit will make the Rat less vulnerable to outbursts of passion. Calm and efficient, the Rat/Rabbit illustrates the aphorism 'Better to risk an intelligent friend than indulge a stupid one.'"],
    "Dragon": [
      "This is a lucky combination, for the Dragon is an excellent companion for the Rat. The voyage will be magical. In deepest harmony with himself, the Rat will leave his bottomless depths and will ride his scaled companion across the Milky Way, his muzzle in the stars. But be careful! If you allow yourself to be spellbound by the Dragon within you, you will pay dearly for it. You idolize him; he is fond of you. He reassures you; but in the end makes your decisions for you. The Dragon is prone to terrible rages; you will hide away. You must know how to make the most of your luck. Imagine it as a voyage in the watery depths and through the heavens, which also embraces the terrestrial world and its deeper recesses. Only do not forget that sometimes you must fight the Dragon in order to prevail, and that he is a ferocious sentinel.",
      "Here is a Companion strong enough for the Rat, master of forces from below."
    ],
    "Snake": [
      "These two are brothers, but they fight each other mercilessly. Their territory is identical, but they have won it with bites and scratches, venom and trickery. The Rat and Snake are masters of the art of attack; moreover they are intuitive, professional spellbinders, who run the risk of putting each other to sleep by using mutual hypnosis. Alas, in this situation, the Rat cannot reverse roles.",
      "The Snake will not lend himself to this little game. For the Rat the Snake Companion will always remain a mysterious reptile, coiled up under a stone, waiting to drag him at times into perilous labyrinths."
    ],
    "Horse": [
      "This coupling brings about an interchange between ardour and prudence. The Rat/Horse will go on often tumultuous voyages. What battles lie in wait! It will be difficult to temper the ardour of the Horse galloping under the blazing sun, while the anxious and prudent Rat will be busy securing his underground fortresses.",
      "The ill-loved Rat must take dark and twisting paths to reach the light, while, for the Horse, it is intolerable to gallop in the shade. He needs the luminous Royal Way, and seeks the crowd and worldly success. The poor Rat must, however, straddle this charger and accept him as his guide. Lacking the power to bridle the magician, the Rat can always discover the joys of riding."
    ],
    "Goat": [
      "Here is an excellent Companion for the Rat, very different from him, whose nature is lighthearted and free from care. An intuitive and subtle artist, the Goat will be prodigiously therapeutic for our ill-loved and anxious rodent. Moreover, the Goat responds to charm and appreciates sympathetic magic, and will not be bored by these qualities in the Rat.",
      "Both will have a tendency to float about in a world of illusions, but, since they will get something worthwhile out of it, it is no matter if they seem blind and deaf; for these two it can be a useful technique."
    ],
    "Monkey": ["Before leaving a trip, these two should prepare a first aid kit; their journey is more likely to resemble a hazardous undertaking than an agreeable outing. These two companions believe in the principle of 'an eye for an eye, a tooth for a tooth' and repay each other accordingly. The Monkey will have but one idea: to devour the small rodent. The Rat will use all his tricks, including the most perverse, to make his companion fall into physical, moral and even spiritual traps. These two strange companions will have no tenderness for each other and will give each other no respite. Their journey will become an encounter staged in a prize-fighter's ring, where all blows are allowed and no rules are observe. May the more formidable win!"],
    "Rooster": ["The Rooster, announcing the rising of the sun, and the Rat, busy with his nocturnal activities, are two companions who will hardly have time for sleep. For these two dissimilar characters, a true understanding may seem impossible, yet it is precisely in this that they may prove to be complementary to each other. The Rooster will perch; the Rat will burrow. Each has a lively nature. The one is a sun symbol, the other a symbol of the night. They will mutually strengthen each other. Rat will offer his world of the underground on a gold platter to the Rooster at the very moment when the Rooster, ruffling his feathers, is rising on his spurs awaiting the moment of dawn's song. This is a daily offering on which the Rat would do well to meditate. For Master Rat, so often taking but rarely giving, this generous Rooster will be a source of strength, if he knows how to take what is offered."],
    "Dog": [
      "He can be the ideal Companion for the Rat. The Dog is the guide for souls during their 'voyages' and is the guardian of the beyond. Like the rodent, he moves between subterranean and invisible worlds. He is, moreover, a faithful and mysterious Companion, slightly pessimistic for, symbolically, he is often associated with the idea of death. Since the Rat shares this association, the Dog's presence is not always welcome.",
      "Perhaps one day the Rat will try to kill the Dog within him and, in battling against this guardian of the gates, he will break through his constraints. The Companion is sometimes a victim who must be sacrificed during the voyage."
    ],
    "Pig": [
      "On the one hand, the Pig is eager to cultivate the art of solitude. He will avoid the main routes, preferring bushy paths with their odour of humus and a quiet night lying under the stars. On the other hand, a Rat/Pig is a complete materialist. Hoarder and profiteer, he will know how to capitalize not only on money, but on the fruits of his experiences.",
      "The Rat/Pig will know only white or black; for him there are no shades of grey, no half-measures. His route will be scattered with obstructions which he will ruthlessly overcome. Do not count on him to have scuples; he will not know the meaning of the word.",
      "Be careful! The Pig is credulous and this, added to the curiosity of the Rat, will spring a few traps. So, Rat/Pig, before you set forth, lay in your provisions of cheese and acorns."
    ]
  },
  "Ox": {
    "Rat": ["Here the Companion is a striking example of a pseudo guardian angel. The aggressions of the Rat are tempered by the tranquil force of the Ox. The Rat explores in depth, the Ox on the surface. Both being creators, it is the Ox who sometimes, by butting with his horns, will force the Rat to leave his underground passages, jostling him from his fortifications. A love of liberty, the Buffalo will rarely be sidetracked. If the Rat symbolizes perpetual movement, the other symbolizes slowness; and if Ox dreams of virgin territory, the Rat dreams of impenetrable universes. The Ox/Rat will be realistic, prudent and will know how to reinforce his success."],
    "Ox": ["Often a recluse and habitually drawn to isolation and retreat, the Ox is barely able to support his own company. A lover of liberty, always on the search for new lands and virgin soil, the Ox/Ox will be fiercely individualistic and original. He will often disconcert his companions, to whom he will be as sparing of tact as of understanding. Such an unwillingness to compromise borders on sheer egotism. The Ox/Ox belongs to the race of conquerors: nothing can constrain nor attach him."],
    "Tiger": ["Born under this alliance, seduction will be your major art. You are hardly likely to lose your way or fall asleep on the march. Conqueror of virgin lands and lord of the jungle, it will be extremely difficult to follow your track, for you are ferociously independent. Imagine a hunter joined to a dreamer, combining intelligence with muscular suppleness. But, Royal Tiger or not, you are also the symbol of temperance. Along with the tenacity and equilibrium of the age-old Ox, you bear within you a potential for sovereign and indomitable power. Alas, modesty and tenderness are not your strong points."],
    "Rabbit": ["A home-loving conqueror! The route will be difficult: the Ox/Rabbit will oscillate between anger and silence, and will hesitate between leaving entirely and retiring into contemplation. If at times the Rabbit element is a sort of ball-and-chain on the Ox, this will have its uses. Knowing in certain situations how to inspire prudence, calm anger and unknot nerves, the Rabbit can soften the stubbornness in which the Ox becomes entangled and stifled. Meanwhile, Ox will teach his Companion that real space and liberty cannot be measured by surface area alone, such as the size of the Rabbit's burrow. Which will win out - prudence or stubbornness? Take care, Ox/Rabbit, you are in danger of going round the world without leaving your room."],
    "Dragon": ["A poisoned gift! A Dragon is always synonymous with luck, but, alas, there is a negative element, above all for a solitary and independent Ox. The Dragon is extremely intelligent but he is inclined to impose his own patterns of life on others. Always on the move, he will do his best to drag the Ox into spaces and dimensions which do not conform to his desires. He will be roused to a fury, which the Ox will oppose with stubborn silence: he is a provoker and able to set the Ox's teeth on edge, and he will have a tendency to goad him; the Dragon dreams of liberty, but it is not the same as his. The Ox/Dragon must therefore take upon himself these two powerful poles, these two disparate forces which inhabit him. Their pressures may be seriously perturbing. Particularly dynamic activity - military, sports or intellectual - may enable the Ox/Dragon to harmonize these contradictory energies."],
    "Snake": ["The Ox will often be disorientated by the aggressiveness of his Snake Companion, who can nurture a dormant capacity for violence in him. The peaceful Ox, his eyes fixed on the blue line of the horizon, will not understand the behaviour of the reptile - his attacks, his secret hiding places, his sinuous approach. He will too often be tempted to crush him with a hoof, and in consequence will suffer many internal conflicts. The slow Ox, however will be stimulated by this mysterious reptile who lures him to a fen and then shows him how he waits, hidden beneath a stone. Although his Snake Companion disconcerts him, the Ox will certainly learn that there are paths that he must sometimes avoid."],
    "Horse": ["Shifting from ardour to slow deliberation and back, these two Companions will not share the same concept of their path. The Ox, sure of himself and restrained, likes to take his time; his progress is slow and he is therefore unwilling to put up with the ardent spirit of the Horse, who goads him on, dreaming of honour and sunlit lands while the Ox ruminates on mapped-out paths. The conscientious Ox, desirous of solitude, grinds his teeth in annoyance when faced with the unmethodical and instinctive side of the Horse and his love of crowds and spectacles. Will the Horse's 'fire' heat the body and soul of this Ox, who is sometimes too 'buried' in his earth? If the Ox/Horse can agree on division of labours, he will undeniably hold winning cards. At work, to the seriousness, thoroughness and perseverance of the Ox will be added the passion and creativity of the Horse. On an emotional level, the ardour and vivacity of the Horse will soften the Ox's hard shell of doubt."],
    "Goat": ["A little note of capriciousness on the part of our Ox. The light-hearted and carefree Goat will be an excellent Companion. With him, the Ox will remove his blinkers and his deep furrows will be adorned with wild flowers and bouquets of brambles. Retaining a degree of gravity, the Ox/Goat will be capable of unexpected capers. The route will therefore be fascinating, provided that the Ox/Goat knows how to maintain a healthy balance between the real and the fantastic."],
    "Monkey": ["The Ox will not resist the Monkey's charm, nor his persuasive and sympathetic magic for very long. Some good advice: if you want peace, give him the illusion that he is stronger but remain attentive and sympathetic. This courageous animal is remarkably agile; physically and mentally he is a first-rate acrobat and gifted with a rare power of persuasion. Take care, for the Monkey is sometimes a sorcerer, capable of transforming all the power of the Ox into mere confetti and mirages."],
    "Rooster": ["The Rooster will add a little wine to his water, or more exactly, he will add a pinch of generosity to his egotism. The Rooster has a sense for sharing and for friendship; admittedly he can behave like a braggart, but then his very ardour and vivacity are so charming that one forgives him everything. From his bravado the Ox will gain a great deal. The morning song of the Rooster will relieve the Ox of a certain torpor and dullness. The ideal would be composed of the Rooster's sharpness on the surface and the Ox's ability in depth."],
    "Dog": ["Here is an amalgam that is a little special, for the pessimism of the Dog, added to the slowness and austerity of the Ox, may result in an exceptional and somewhat forbidding gravity. The Dog is the ancient guardian of the Underworld, the Ox of the Labyrinth: this combination of Cerberus and Minotaur will be a bit disquieting. Yet the Dog can bring to the Ox a perspective and power of introspection which he often lacks. The Ox, for his part, will alleviate the doubts, the existential qualms and the tortured questions of the Dog. The Ox/Dog will thus obtain both hope and lucidity; he will know himself a little better, which is the beginning of true wisdom."],
    "Pig": [
      "Both the Ox and the Pig are sometimes slightly egotistical recluses. One is the symbol of fertility, the other of abundance. Their voyage will have every chance of material comfort, but there will be complications. With the Ox in charge, you will face the everyday world with a severe and uncompromising appearance; this will conceal your real life of secret corners and cosy beaches - so enjoyable, luxurious and unconstrained, and made even more pleasurable by discreet weekends, private clubs and closed circles.",
      "If the Pig is in charge, then under the facade of a man who enjoys life to the fullest, will lie an indestructible solidity and an unsuspected tenacity which will often make you all the more formidable, especially in business. Some will think they can soften you up by various means; you will appear all smiles, but inside you will remain glacial."
    ]
  },
  "Tiger": {
    "Rat": ["When a rodent is coupled with a carnivorous animal, the voyage will not be very peaceful; count on the Tiger, he will see to it that you do not fall asleep on your laurels! The hunt is his domain, the jungle his universe; the way will be strewn with traps and nothing will escape his vigilance. As a sentinel, he is unsurpassed. However, do not forget that the Tiger is a noble lord, who will expect to be first. In roaming various territories, he will appropriate them, and the individualistic Rat nature will respond with a violent revolt, which may result in your being emotionally torn. Do not despair. The Tiger is also a symbol of moderation. He is an excellent guide, in every sense of the term, and the Rat, at times a usurper himself, will gain in tolerance and loyalty."],
    "Ox": ["Born under this alliance, seduction will be your major art. You are hardly likely to lose your way or fall asleep on the march. Conqueror of virgin lands and lord of the jungle, it will be extremely difficult to follow your track, for you are ferociously independent. Imagine a hunter joined to a dreamer, combining intelligence with muscular suppleness. But, Royal Tiger or not, you are also the symbol of temperance. Along with the tenacity and equilibrium of the age-old Ox, you bear within you a potential for sovereign and indomitable power. Alas, modesty and tenderness are not your strong points."],
    "Tiger": ["This animal is a traveller who will keep within his own particular territory, his beloved jungles. A lordly hunter who trusts in his lucky star, he will tend to take over territories for his sole use, relying on fortunes and his prestige to buttress and establish his claims. He risks becoming difficult to deal with beneath his handsome and special fur, that symbol of Yin and of Yang whose principle of alternation, he should respect. He will pay dearly if he forgets to do so. His twin signs, blazoned with the same royal stamp under the same striped coat, can only affirm his particular quality of moderation: so he should pull in his claws and hide his fangs."],
    "Rabbit": ["Be careful of this animal; its appearance is deceptive. All gentleness on the outside - softly furry and velvety - he is mistakenly trusted. What makes the Tiger makes the Rabbit, and what makes the Rabbit makes the Tiger - all the better to eat you up. The Rabbit in the skin of a Tiger will find himself perfectly at ease; as for the Tiger, what could be easier than to give the illusion of being a harmless, large, striped tomcat. Essentially, game for the Tiger/Rabbit will involve sowing illusions and creating confusion among other animals; imagine Rudyard Kipling's Tiger meeting up with Bugs Bunny."],
    "Dragon": ["Not one to fall asleep on his way, this terrestrial and celestial mount will be secretive and enigmatic, spreading fear along his route. His isolated condition will compel him to follow his peculiar destiny. The Tiger will awaken the Dragon sleeping deep in a magic grotto; the Dragon will often provoke the Tiger to combat. The Tiger/Dragon is an animal that uses his claws, scales and formidable teeth, sometimes spitting fire. Yet he has a tendency to so overdo things that he can appear a clown. He should be careful of this, by which he may forfeit the fear and respect his majestic appearance inspires. Although it may amuse others to see him clowning, he is not the type - and should not do it."],
    "Snake": ["He is the professional charmer, crafty and sly if the need arises, capable of biting and releasing venom in order to attain his ends. However, moderation will win out over the ill-loved Snake's aggressiveness. Coiled within the Tiger, he can also be a welcome symbol of knowledge and of the underground world. Habituated to the honour due his rank, the Tiger is sometimes forgetful of those who crawl yet accomplish the same ends. The Snake who lies within may pretend humility; this is easy for him, since he is a prince of detours and winding paths. However, he should be careful not to fall into the traps he sets for others."],
    "Horse": ["Spirited but temperate, alert to traps and clearing all obstacles, the Tiger/Horse will accomplish a voyage in which enthusiasm will be joined with patience, and stalking with slyness and galloping. Prudence and balance, calmness and patience will be difficult for the ardent Horse who sleeps within the Tiger: the Horse prefers the sunlit route and applause to the luxuriant semi-obscurity of the jungle. But the Tiger will quickly bring him back to reality; life is more than turning round in circles in a riding-school ring."],
    "Goat": ["A dreamy and artistic Tiger; a wild beast among a mass of clouds, leaping astride the stars. That may make the Tiger/Goat smile, and he has a need to. If he loses his Tiger side, which is sometimes too solemn, he will discover that the route can be beautiful - if he travels with his nose raised to the heavens. So, the Tiger should not devour the Goat within him; rather, he should let him caper about his head and his heart; his imagination will bring romance, which will reduce all difficulties to the level of a game."],
    "Monkey": ["Games of hide-and-seek, tricks and hoaxes will blend with feline stratagems and bravery. That sorcerer the Monkey has more than one trick up his sleeve. Depend on him to transform you into a skillful tightrope walker or a dazzling juggler. As playful as the Goat, the game with him is one of getting you to accomplish what he has decided you should accomplish. The Tiger/Monkey is thus a formidable animal which, combining the proud bearing and temperate skills of the Tiger with the ever-present wizardry of the little Monkey, can be counted on to turn anything upside down and provoke many a sleepless night. For the Monkey, leaping unobserved from branch to branch in the jungle with his eyes shut, one cannot aply the usual formula, 'put a Tiger in your tank'. Rather, 'wrap a Tiger within the skin of a mischievous Monkey, and then you will really see something...'"],
    "Rooster": ["He detests banality. His creed is based on the need to be first and to dominate. He is unequalled where the question of pride is concerned; be careful, a voyage is always beset with traps and surprises. The Tiger/Rooster will have a tendency to believe himself to be the winner every time. Alas, the higher he climbs, the greater the fall and, striving always to be first, he will be in danger of running out of breath."],
    "Dog": ["He is a double guardian: the one protects from demons and the other protects souls in the next world. He is a virtuous pessimist disguised in the skin of a man-eating Tiger. The Tiger/Dog will be a thoughtful animal, at his ease in the 'invisible' world and prudent in his own territory. Sure of himself, but calm and circumspect, his Dog side brings an awareness of time and distance, an idea of the ephemeral as well as a sense of detachment. The Tiger/Dog knows better than anyone that after this voyage there will be another. He should be careful, however, for his feet are not on the ground and his halo is askew."],
    "Pig": ["He will be the symbol of a successful voyage. But then, everything depends on what one calls 'success'. The solitary Pig will lead the Tiger along sombre paths, revealing mysteries and the spiritual world, but he will expect something in return. The Tiger may be a royal lord of the jungle, but the Pig is master of the palace and the symbol of opulence. But what opulence? This unscrupulous hunter will be neither tepid nor moderate; rather, he will be angelic or diabolical. But be careful: those who act like angels sometimes also act like fools."]
  },
  "Rabbit": {
    "Rat": ["This is a curious mixture, to say the least. Are you not these hereditary enemies 'condemned' to travel the same route? But do not be fooled, for this may be the best way to accomplish the voyage. An apprehensive Rat coupled with the eternally stalking Rabbit will not be easily deceived. Suspicious, both adaptable and aggressive, he will be ready to protect himself from predators and to go to any lengths to secure his comfort and vested interests. Also, the influence of the Rabbit will make the Rat less vulnerable to outbursts of passion. Calm and efficient, the Rabbit/Rat illustrates the aphorism 'Better to risk an intelligent friend than indulge a stupid one.'"],
    "Ox": ["A home-loving conqueror! The route will be difficult: the Rabbit/Ox will oscillate between anger and silence, and will hesitate between leaving entirely and retiring into contemplation. If at times the Rabbit element is a sort of ball-and-chain on the Ox, this will have its uses. Knowing in certain situations how to inspire prudence, calm anger and unknot nerves, the Rabbit can soften the stubbornness in which the Ox becomes entangled and stifled. Meanwhile, Ox will teach his Companion that real space and liberty cannot be measured by surface area alone, such as the size of the Rabbit's burrow. Which will win out - prudence or stubbornness? Take care, Rabbit/Ox, you are in danger of going round the world without leaving your room."],
    "Tiger": ["Be careful of this animal; its appearance is deceptive. All gentleness on the outside - softly furry and velvety - he is mistakenly trusted. What makes the Tiger makes the Rabbit, and what makes the Rabbit makes the Tiger - all the better to eat you up. The Rabbit in the skin of a Tiger will find himself perfectly at ease; as for the Tiger, what could be easier than to give the illusion of being a harmless, large, striped tomcat. Essentially, game for the Rabbit/Tiger will involve sowing illusions and creating confusion among other animals; imagine Rudyard Kipling's Tiger meeting up with Bugs Bunny."],
    "Rabbit": ["He is a mysterious and enigmatic animal, who cultivates a pronounced taste for secrecy; nothing is simple or self-evident for him. Morbidly prudent (he will plan his route meticulously, foreseeing a host of eventual difficulties and how to avoid them), his journey will be transformed into a marathon. Do not hope to get the better of him while he is asleep: he sleeps with one eye open and the other on the look-out. The Rabbit/Rabbit will be a great seducer, refined and perceptive, but beneath his velvet paws, his claws are never completely drawn in. This lover of hiding places and comfortable nooks should overcome his fear of giving himself in a relationship; otherwise he may end up in a lonely corner."],
    "Dragon": ["This companion will bring him self-confidence, and he will feel his wings growing, be they made of lace or scales. The Rabbit/Dragon will be audacious, equipped with a lively and shrewd intelligence. He will be a seductive prince endowed with a complex brain; a mysterious being gliding among fairy-like worlds and parallel universes. However, he should be wary of a type of aggressiveness revealed in an attitude of 'I know everything; I have seen everything'. He is the guardian of a secret or treasure and has the soul of a fantasist; a lunar vagabond with magical powers, in search of the marvellous."],
    "Snake": ["A strange creature, whose head is not easily distinguished from its tail. In love with anything strange, but not an adventurer, the Rabbit/Snake will daydream about travelling while curled up in a soft armchair. 'Inhabited' by a prince of wanderings, he has a taste for suspense, mystery and the subterranean, discovering hiding places buried under a stone. He will not hesitate to take on the colour of a wall for the pleasure of deceiving, surprising and disconcerting you. Elusive, clever and shifty, he is as dangerous as he is seductive. If you meet up with a Rabbit/Snake, pinch yourself, because he is a professional spell-binder. He will seduce you somehow - with his charm or by blackmail."],
    "Horse": ["Something of an unprincipled opportunist, he will be slightly mystifying. Irresistibly attracted by all that glitters, he will alternate between being impetuous and prudent. The Rabbit/Horse is a winner; he refuses to run for cover, even when security requires it. For him, a thrilling route is a necessity, and he obtains his goals. This war-horse will not allow others to step on his toes or obstruct him."],
    "Goat": ["He will be a sweet dreamer, living far from reality in a world of clouds. If he cannot find the comfort which is so dear to him, he will seek it in his dreams. He will love travel, always seeking something more marvellous. He has a supple nature and is intuitive and charming; nothing will seem to ruffle him, for he has the gift of assimilating the most trying situations into his creative universe. Both collar and leash will be rejected by the Rabbit/Goat for he is the type who is always on the loose, ever-ready for adventure."],
    "Monkey": ["He will be an inventive, lively, rather airy animal. He will have a tendency to be calculating, and will leave nothing to chance. He prefers being a schemer, conjurer and scrounger to labourious and irksome work. The Rabbit/Monkey envisages life as a game which, for the fun of it, he himself strews with traps and mirages, the better to zigzag between them. To attain his ends, he throws scruples to the wind. He will not hesitate to cheat, but who is he deceiving? He does not know himself, unless one day the Sphinx asks him the question."],
    "Rooster": ["He will always keep his eyes peeled. He must always be entitled to the right to look, to control a situation and to feel he is the master of his destiny. He is not the kind to let himself be guided. He is a curious mixture in which the call of the dawn is coupled with the murmurs of the night. The voyage will be profitable if the prudence of the Rabbit is allied with the tenacity and loyalty of the Rooster. The Rabbit/Rooster is a generous, lively animal with a pure heart. His spur and his claw will be used defensively rather than offensively."],
    "Dog": ["In this person the Dog element should be recognized as a guide and guardian, a faithful Companion into the invisible world which lies beyond the voyage of life. The egotistical Rabbit will discover that a precious ally lies within him. The Dog/Rabbit is circumspect, sometimes to the point of sickly distrust. While the sun may be shining on him, he will still be thinking only of the darkness to come. This animal is incapable of living in the present and has a tendency to become obsessed with past failures and future difficulties. He will weep for himself, his often imagined ills, and be depressed by the size of his task! In such moods he is incapable of looking at the simple spectacle of life going on around him, let alone enjoying it."],
    "Pig": ["A solitary animal who is slightly disquieting but perfectly organized. There exists an air of mystery about him; one never knows the real truth. Amassing great wealth, he lives in luxurious comfort but without neglecting the cultivation of his mind. Seductive, he is given to good and bad excesses, a distinction he prefers to ignore. If you corner him, he may either slip away or attack - unless he merely gives you a reply that leaves you breathless. This Rabbit/Pig is often master of a palace of mirages constructed on a base of others' gullibility."]
  },
  "Dragon": {
    "Rat": [
      "This is a lucky combination, for the Dragon is an excellent companion for the Rat. The voyage will be magical. In deepest harmony with himself, the Rat will leave his bottomless depths and will ride his scaled companion across the Milky Way, his muzzle in the stars. But be careful! If you allow yourself to be spellbound by the Dragon within you, you will pay dearly for it. You idolize him; he is fond of you. He reassures you; but in the end makes your decisions for you. The Dragon is prone to terrible rages; you will hide away. You must know how to make the most of your luck. Imagine it as a voyage in the watery depths and through the heavens, which also embraces the terrestrial world and its deeper recesses. Only do not forget that sometimes you must fight the Dragon in order to prevail, and that he is a ferocious sentinel.",
      "Here is a Companion strong enough for the Rat, master of forces from below."
    ],
    "Ox": ["A poisoned gift! A Dragon is always synonymous with luck, but, alas, there is a negative element, above all for a solitary and independent Ox. The Dragon is extremely intelligent but he is inclined to impose his own patterns of life on others. Always on the move, he will do his best to drag the Ox into spaces and dimensions which do not conform to his desires. He will be roused to a fury, which the Ox will oppose with stubborn silence: he is a provoker and able to set the Ox's teeth on edge, and he will have a tendency to goad him; the Dragon dreams of liberty, but it is not the same as his. The Dragon/Ox must therefore take upon himself these two powerful poles, these two disparate forces which inhabit him. Their pressures may be seriously perturbing. Particularly dynamic activity - military, sports or intellectual - may enable the Dragon/Ox to harmonize these contradictory energies."],
    "Tiger": ["Not one to fall asleep on his way, this terrestrial and celestial mount will be secretive and enigmatic, spreading fear along his route. His isolated condition will compel him to follow his peculiar destiny. The Tiger will awaken the Dragon sleeping deep in a magic grotto; the Dragon will often provoke the Tiger to combat. The Dragon/Tiger is an animal that uses his claws, scales and formidable teeth, sometimes spitting fire. Yet he has a tendency to so overdo things that he can appear a clown. He should be careful of this, by which he may forfeit the fear and respect his majestic appearance inspires. Although it may amuse others to see him clowning, he is not the type - and should not do it."],
    "Rabbit": ["This companion will bring him self-confidence, and he will feel his wings growing, be they made of lace or scales. The Dragon/Rabbit will be audacious, equipped with a lively and shrewd intelligence. He will be a seductive prince endowed with a complex brain; a mysterious being gliding among fairy-like worlds and parallel universes. However, he should be wary of a type of aggressiveness revealed in an attitude of 'I know everything; I have seen everything'. He is the guardian of a secret or treasure and has the soul of a fantasist; a lunar vagabond with magical powers, in search of the marvellous."],
    "Dragon": ["A route strewn with scales, volcanic earth and tumultuous torrents; the Dragon/Dragon will have a tendency to transform his 'voyage' into a competition in which he must, of course, arrive the victor. It is useless to try to stop him; he will walk right over you and remain deaf to your advice. This animal should learn to relax, otherwise he may 'crack up' en route. Alas, he refuses to listen; he believes in his lucky star, retires into his shell and spits fire. It is advisable that he tone down his showy behaviour - unless he wants a career on the stage."],
    "Snake": ["A lucky and canny animal, the Dragon/Snake is a traveller on whom fortune will smile, and what he cannot obtain by force or charm he will obtain by malice and enchantment. If the Dragon sometimes makes the mistake of being too heavy or conventional, the Snake will lead him to value discretion, patience and the advantages of the indirect approach. A formidable beast, full of charm, he will bring a taste of mystery to his partner, who will shiver either with pleasure or with fear."],
    "Horse": ["Riding may have its charms, but there are inherent dangers in mounting a Dragon which are best avoided, even if he is the companion of a Horse. An impetuous and ardent animal, the Dragon/Horse combines elegance with opportunism, luck with lively intelligence. Few can mount him. The ride will be a sort of mad race in which he may often conquer and attract admiration; but the speed of it all will tend to go to his head and his extraordinary luck make him mad. He needs to learn about that rare flower called modesty; even then, he must be careful not to trample on it while jumping for joy when its bloom is full."],
    "Goat": ["Imagine a terrifying animal - one with multi-coloured scales who spits fire, but wears beautiful boots and is crowned with graceful horns. The Dragon/Goat appears thus, but also very much at ease with himself. The Goat brings reality and substance to the Dragon's wildest dreams, offering him fantasy, imagination and a sense of the marvellous on a platter of clouds. This often too serious Dragon will learn to relax and enjoy himself. The Dragon/Goat, an animal of all territories, will not be merely a complex and well-regulated machine, but will be able to take to the air, becoming a Dragon of subtle azure, soft breezes and capricious clouds."],
    "Monkey": ["Possessing a combination of the supremely gifted synchronized with a talent and taste for walking the tightrope, the Dragon/Monkey - a valiant and fearless guardian - will never unbuckle his armour. Always prepared for war, his days and nights are spent in a state of alertness, much to the continued astonishment of his friends. Alas, he tends to be an extortioner. He has charm, is brilliant and his intelligence is remarkable, but his main defect is his immoderate pride. His company is appreciated, but only in small doses. He will be a phenomenon and his collaboration and assistance will be desired, but you will not be able to breathe freely until you have seen the back of him. So, unwind a little, be natural and glance on your fellow creatures with a less condescending eye."],
    "Rooster": ["He only feels at ease in a high position, both in the geographic and the hierarchical sense of the term. He prefers the top of a tower or a top floor with terrace. The Dragon/Rooster will always be in the first row and nothing will escape his vigilant gaze; he will wish to dominate, control and supervise in all circumstances. He will be kind and possess originality, qualities which the Rooster does not always naturally cultivate. He will also be irresistibly charming."],
    "Dog": ["He is one of those who inspire confidence, and with reason: one can give him one's friendship wholeheartedly and rely on his word. The Dragon/Dog is a loyal, dedicated and faithful animal who appreciates the luck available for him throughout life, not taking it as his due, but as a gift from Providence. The Dog will understand the value of the Dragon sleeping with him; he, in turn, will give to the Dragon a sense of context, humour and an understanding of a subtle world which includes an interior dimension usually incomprehensible to the Dragon. For the Dragon is always on tenterhooks; usually, he cannot pause to reflect, yet alone contemplate or meditate, and has little contact with the invisible and the hereafter."],
    "Pig": ["A solitary wanderer, seeking a treasure that perhaps he did not know how to protect. The Dragon/Pig will tend to gain material and spiritual wealth. Alas, it does not suffice simply to possess matter or mind and spirit - they must be given meaning. Do not sleep before your safe, before the gates of your palace or on the threshold of your mysterious grotto. Ask yourself whether the safe, palace or grotto may be empty; in which case, it is up to you to fill them."]
  },
  "Snake": {
    "Rat": [
      "These two are brothers, but they fight each other mercilessly. Their territory is identical, but they have won it with bites and scratches, venom and trickery. The Rat and Snake are masters of the art of attack; moreover they are intuitive, professional spellbinders, who run the risk of putting each other to sleep by using mutual hypnosis. Alas, in this situation, the Rat cannot reverse roles.",
      "The Snake will not lend himself to this little game. For the Rat the Snake Companion will always remain a mysterious reptile, coiled up under a stone, waiting to drag him at times into perilous labyrinths."
    ],
    "Ox": ["The Ox will often be disorientated by the aggressiveness of his Snake Companion, who can nurture a dormant capacity for violence in him. The peaceful Ox, his eyes fixed on the blue line of the horizon, will not understand the behaviour of the reptile - his attacks, his secret hiding places, his sinuous approach. He will too often be tempted to crush him with a hoof, and in consequence will suffer many internal conflicts. The slow Ox, however will be stimulated by this mysterious reptile who lures him to a fen and then shows him how he waits, hidden beneath a stone. Although his Snake Companion disconcerts him, the Ox will certainly learn that there are paths that he must sometimes avoid."],
    "Tiger": ["He is the professional charmer, crafty and sly if the need arises, capable of biting and releasing venom in order to attain his ends. However, moderation will win out over the ill-loved Snake's aggressiveness. Coiled within the Tiger, he can also be a welcome symbol of knowledge and of the underground world. Habituated to the honour due his rank, the Tiger is sometimes forgetful of those who crawl yet accomplish the same ends. The Snake who lies within may pretend humility; this is easy for him, since he is a prince of detours and winding paths. However, he should be careful not to fall into the traps he sets for others."],
    "Rabbit": ["A strange creature, whose head is not easily distinguished from its tail. In love with anything strange, but not an adventurer, the Snake/Rabbit will daydream about travelling while curled up in a soft armchair. 'Inhabited' by a prince of wanderings, he has a taste for suspense, mystery and the subterranean, discovering hiding places buried under a stone. He will not hesitate to take on the colour of a wall for the pleasure of deceiving, surprising and disconcerting you. Elusive, clever and shifty, he is as dangerous as he is seductive. If you meet up with a Snake/Rabbit, pinch yourself, because he is a professional spell-binder. He will seduce you somehow - with his charm or by blackmail."],
    "Dragon": ["A lucky and canny animal, the Snake/Dragon is a traveller on whom fortune will smile, and what he cannot obtain by force or charm he will obtain by malice and enchantment. If the Dragon sometimes makes the mistake of being too heavy or conventional, the Snake will lead him to value discretion, patience and the advantages of the indirect approach. A formidable beast, full of charm, he will bring a taste of mystery to his partner, who will shiver either with pleasure or with fear."],
    "Snake": ["Whether a rattlesnake, cobra or adder, he will prefer detours and by-ways to the main roads. But the result will be the same: he will arrive - slowly but surely - at the goal he has fixed for himself. The Snake/Snake will be unable to avoid complicating his life. When it seems too simple, he becomes bored; he always needs a little salt, a tasty sauce, because he is a complicated animal. Always on the defensive and slightly aggressive, he ardently cultivates a sense of property through his home which he makes a veritable refuge, an Ali Baba cavern, piling up treasures which he jealously protects. If you sight him on your path, make a detour; even if you are not afraid of him, your reaction will give him so much pleasure!"],
    "Horse": ["He is a wise dandy, combining elegance and ardour with highly developed moral demands which can sometimes conflict with his pride. For the Snake/Horse is a bad loser and does not accept failure. He is a winner and will not hesitate to be opportunistic and sly, restraining neither his tongue nor his heart. Nevertheless, since he is irresistibly charming, the Snake/Horse will be excused for his boastfulness and even his ill-nature. But he should not overdo it!"],
    "Goat": ["It will be rather dangerous to fall in love with him: it is impossible to expect fidelity from the Snake/Goat. This reptilian Goat is a fickle being charged with fantasy; an artist who will make a 'goat' of you if you try to seduce him. At first he will seem docile, seeking your protection: but he will then pull you joyously along by the tip of your nose. Exclusive and jealous, he is scarcely aware of the contradiction, for his own bad faith is disarming. In life he will enjoy plenty of good luck and have the advantage of good taste and a capacity for finesse; but his instability will cause him considerable damage, some of which he will not recover from, above all during his mature years."],
    "Monkey": ["He will be rational and a good organizer, but he will not be able to conceal his strong superiority complex which, unless he takes care, will cause him major problems. An intelligent and quick animal, his tendency to get carried away will be tempered by deep reflection; even so, he will always refuse to listen to the advice of others, because of his pride and self-esteem. He will not entertain any argument about his ideas, still less that his work or his word be questioned. The Snake/Monkey is talkative, courageous and, at times, a liar. However, his ability and his subtlety are major trump cards."],
    "Rooster": ["An intuitive and frank animal, he will accomplish his tasks with a generous heart and with much good will and honesty - thus correcting the Snake's tendency to side-track - which will not prevent him from being uneasy, despite his apparent self-assurance. The Snake/Rooster flares up easily, so be careful if it is one if his bad days. He will attack with surprising aggressiveness and be entirely unjust simply to reassure himself. Do not attempt to expose his faults with evidence; he will be narrow-minded and never forgive you for having discovered his weak points. The Snake/Rooster is overly concerned with projecting a good image. He has a need to shine and surround himself with costly and beautiful things; this may appear superficial, but it is vital for his morale."],
    "Dog": ["He has a keen moral sense, is intuitive, but has a tendency to be pessimistic. Life with him can become very complicated. He is the kind to torment himself to excess, announcing the onset of a hurricane at the least rising of the wind, or a deluge after a few drops of rain. Ever on the watch and constantly on guard, he risks playing the role of the persecuted, one of those flayed alive, whose company one does not usually seek. This is a drawback, particularly since the Snake/Dog is courageous, warm and understands the meaning of faithfulness. However, he has a great need of love and reassurance."],
    "Pig": ["While he is peaceful, secretive and sensitive, he is also a bad loser and his motives are questionable. He does not like to lose and prefers solitude to risking failure. It is useless to try to distract him from his normal routine; he is too obstinate and distrustful. However, this does not stop him from being gullible. It is quite possible to 'take him in'; he will then oscillate between aggressiveness and running away, for at bottom he is tolerant but too proud to admit that his adversary may be right. Although he appears indifferent, the Snake/Pig actually loves money for its own sake and adores amassing treasures and booty. Apparently calm, deep within he is boiling. This solitary reptile is not lukewarm: he is a tough person with a tender heart."]
  },
  "Horse": {
    "Rat": [
      "This coupling brings about an interchange between ardour and prudence. The Horse/Rat will go on often tumultuous voyages. What battles lie in wait! It will be difficult to temper the ardour of the Horse galloping under the blazing sun, while the anxious and prudent Rat will be busy securing his underground fortresses.",
      "The ill-loved Rat must take dark and twisting paths to reach the light, while, for the Horse, it is intolerable to gallop in the shade. He needs the luminous Royal Way, and seeks the crowd and worldly success. The poor Rat must, however, straddle this charger and accept him as his guide. Lacking the power to bridle the magician, the Rat can always discover the joys of riding."
    ],
    "Ox": ["Shifting from ardour to slow deliberation and back, these two Companions will not share the same concept of their path. The Ox, sure of himself and restrained, likes to take his time; his progress is slow and he is therefore unwilling to put up with the ardent spirit of the Horse, who goads him on, dreaming of honour and sunlit lands while the Ox ruminates on mapped-out paths. The conscientious Ox, desirous of solitude, grinds his teeth in annoyance when faced with the unmethodical and instinctive side of the Horse and his love of crowds and spectacles. Will the Horse's 'fire' heat the body and soul of this Ox, who is sometimes too 'buried' in his earth? If the Horse/Ox can agree on division of labours, he will undeniably hold winning cards. At work, to the seriousness, thoroughness and perseverance of the Ox will be added the passion and creativity of the Horse. On an emotional level, the ardour and vivacity of the Horse will soften the Ox's hard shell of doubt."],
    "Tiger": ["Spirited but temperate, alert to traps and clearing all obstacles, the Horse/Tiger will accomplish a voyage in which enthusiasm will be joined with patience, and stalking with slyness and galloping. Prudence and balance, calmness and patience will be difficult for the ardent Horse who sleeps within the Tiger: the Horse prefers the sunlit route and applause to the luxuriant semi-obscurity of the jungle. But the Tiger will quickly bring him back to reality; life is more than turning round in circles in a riding-school ring."],
    "Rabbit": ["Something of an unprincipled opportunist, he will be slightly mystifying. Irresistibly attracted by all that glitters, he will alternate between being impetuous and prudent. The Horse/Rabbit is a winner; he refuses to run for cover, even when security requires it. For him, a thrilling route is a necessity, and he obtains his goals. This war-horse will not allow others to step on his toes or obstruct him."],
    "Dragon": ["Riding may have its charms, but there are inherent dangers in mounting a Dragon which are best avoided, even if he is the companion of a Horse. An impetuous and ardent animal, the Horse/Dragon combines elegance with opportunism, luck with lively intelligence. Few can mount him. The ride will be a sort of mad race in which he may often conquer and attract admiration; but the speed of it all will tend to go to his head and his extraordinary luck make him mad. He needs to learn about that rare flower called modesty; even then, he must be careful not to trample on it while jumping for joy when its bloom is full."],
    "Snake": ["He is a wise dandy, combining elegance and ardour with highly developed moral demands which can sometimes conflict with his pride. For the Horse/Snake is a bad loser and does not accept failure. He is a winner and will not hesitate to be opportunistic and sly, restraining neither his tongue nor his heart. Nevertheless, since he is irresistibly charming, the Horse/Snake will be excused for his boastfulness and even his ill-nature. But he should not overdo it!"],
    "Horse": ["Thirsty for voyages and adventures, this impatient and impulsive animal will always be a vagabond and his opportunism and risky undertakings will cause him many problems. Others will envy his natural brilliance and elegance: the Horse/Horse will be eloquent, an effective orator and a natural leader; he will attract honours and prestige. Discretion and secrecy are unknown to him. He will need a clear and untravelled path, which he will try to keep all for himself; an avenue in which he can give free rein to his passions and impulses. He will be loyal and honourable, but his unbridled ambition, egotism and boastfulness will irritate his companions. He should curb himself and learn to be more moderate, countering his ardour and impulsiveness with watchfulness and realism."],
    "Goat": ["Dream worlds and fantasy will flavour this alliance with a slightly capricious and charming bohemianism, favouring an escape towards enchanted domains of azure and clouds alive with fanciful and diaphanous creatures of the imagination. The Horse/Goat will need an epic existence; his ardour will be conquering, but he will prefer art and heroic poetry to war-like expeditions. His personal universe will open to other dimensions - towards subtle inward spaces that no system of logic can define or measure."],
    "Monkey": ["In turn eloquent and courageous, his path will resemble an extended racecourse, from which the Horse/Monkey can only emerge victorious. He will be as well-balanced as a race horse, at once mount and rider; a Don Juan or a hermit - as well as having a touch of Don Quixote - transforming a track into an arena. He will stake his life - from pride, from a delight in taking risks and even from cynicism. Uniting intelligence with a fine appearance, he exploits to the utmost his resources of charm, talent, wiliness and, sometimes, deceit. The Horse/Monkey will often dream of a path haloed by glory and strewn with flowers - that he will stamp upon with superb indifference."],
    "Rooster": ["While distinguished, loyal and generous, he is also vain and lacks modesty. His pride drives him, pushing him on against wind and tide, keeping him far in front of the masses, whom he needs to command and carry with him. The Horse/Rooster likes to stand out from the crowd; he is often unique and possesses a sense of honour to the highest degree; his word is his bond. His generosity can be total, his loyalty irreversible. If he gives you his confidence and friendship, nothing - no pressure nor catastrophe - will weaken it."],
    "Dog": ["Mount and guide, loyal and faithful, he tenaciously makes his way by day and night, prodded by his intuition. Tempering his impatience and his fire and never doubting his abilities, he is still able to question his ideas and actions and thus improve himself. He succeeds in controlling both his pride and his fear of failure, never hesitating to smile at his defects and his weaknesses, yet he remains ardent and passionate. His Dog side allows him to grasp secrets and dimensions that the Horse can reach only rarely and with difficulty - a world of contemplation and self-questioning in which the Horse's ardour is refined and spiritualized."],
    "Pig": ["Endowed with a broad and clear intelligence, the Horse/Pig is well aware of the pride that eats away at him. He has a tendency to overrate the true value of his possessions and conquests, and to overlook their impermanence. He cannot resist collecting 'treasures' which are, in fact, fakes. Actually, he unconsciously seeks a more worthy treasure which lies within him. His ardour and impulsiveness often give way to doubt and mystery, the latter irresistibly attracting him like the promise of a profound accomplishment."]
  },
  "Goat": {
    "Rat": [
      "Here is an excellent Companion for the Rat, very different from him, whose nature is lighthearted and free from care. An intuitive and subtle artist, the Goat will be prodigiously therapeutic for our ill-loved and anxious rodent. Moreover, the Goat responds to charm and appreciates sympathetic magic, and will not be bored by these qualities in the Rat.",
      "Both will have a tendency to float about in a world of illusions, but, since they will get something worthwhile out of it, it is no matter if they seem blind and deaf; for these two it can be a useful technique."
    ],
    "Ox": ["A little note of capriciousness on the part of our Ox. The light-hearted and carefree Goat will be an excellent Companion. With him, the Ox will remove his blinkers and his deep furrows will be adorned with wild flowers and bouquets of brambles. Retaining a degree of gravity, the Goat/Ox will be capable of unexpected capers. The route will therefore be fascinating, provided that the Goat/Ox knows how to maintain a healthy balance between the real and the fantastic."],
    "Tiger": ["A dreamy and artistic Tiger; a wild beast among a mass of clouds, leaping astride the stars. That may make the Goat/Tiger smile, and he has a need to. If he loses his Tiger side, which is sometimes too solemn, he will discover that the route can be beautiful - if he travels with his nose raised to the heavens. So, the Tiger should not devour the Goat within him; rather, he should let him caper about his head and his heart; his imagination will bring romance, which will reduce all difficulties to the level of a game."],
    "Rabbit": ["He will be a sweet dreamer, living far from reality in a world of clouds. If he cannot find the comfort which is so dear to him, he will seek it in his dreams. He will love travel, always seeking something more marvellous. He has a supple nature and is intuitive and charming; nothing will seem to ruffle him, for he has the gift of assimilating the most trying situations into his creative universe. Both collar and leash will be rejected by the Goat/Rabbit for he is the type who is always on the loose, ever-ready for adventure."],
    "Dragon": ["Imagine a terrifying animal - one with multi-coloured scales who spits fire, but wears beautiful boots and is crowned with graceful horns. The Goat/Dragon appears thus, but also very much at ease with himself. The Goat brings reality and substance to the Dragon's wildest dreams, offering him fantasy, imagination and a sense of the marvellous on a platter of clouds. This often too serious Dragon will learn to relax and enjoy himself. The Goat/Dragon, an animal of all territories, will not be merely a complex and well-regulated machine, but will be able to take to the air, becoming a Dragon of subtle azure, soft breezes and capricious clouds."],
    "Snake": ["It will be rather dangerous to fall in love with him: it is impossible to expect fidelity from the Goat/Snake. This reptilian Goat is a fickle being charged with fantasy; an artist who will make a 'goat' of you if you try to seduce him. At first he will seem docile, seeking your protection: but he will then pull you joyously along by the tip of your nose. Exclusive and jealous, he is scarcely aware of the contradiction, for his own bad faith is disarming. In life he will enjoy plenty of good luck and have the advantage of good taste and a capacity for finesse; but his instability will cause him considerable damage, some of which he will not recover from, above all during his mature years."],
    "Horse": ["Dream worlds and fantasy will flavour this alliance with a slightly capricious and charming bohemianism, favouring an escape towards enchanted domains of azure and clouds alive with fanciful and diaphanous creatures of the imagination. The Goat/Horse will need an epic existence; his ardour will be conquering, but he will prefer art and heroic poetry to war-like expeditions. His personal universe will open to other dimensions - towards subtle inward spaces that no system of logic can define or measure."],
    "Goat": ["His sense of reality will be precarious, which does not bother him in the least. The Goat/Goat will love travel and will be ever ready to leap about and cavort. His tendency to be in a state of confusion will attract enemies who dislike his carefree attitude, lack of gravity and disregard for conventions. You can preach to him the errors of his ways as much as you like, but he will escape you with a graceful pirouette, his nose in the air. It is an understatement to say that the Goat/Goat enjoys the good life. Even if his route is strewn with traps, he will never be discouraged, and will take it all with good will, humour and in a free and easy manner."],
    "Monkey": ["Intuitive and intelligent, he will be extremely restless. At times pride will curb his fantasies and his ideas will then gain in constancy and consistency, though there is no certainty that he really wants to pursue them to their logical end. The Monkey likes to leap from branch to branch, and the Goat leaps ceaselessly from cloud to cloud. Thus, their alliance will be particularly lively and eventful. As for love, the Goat/Monkey can be a real heartbreaker!"],
    "Rooster": [
      "Generous and outgoing, this animal will be honest and pure, but, alas, his character will often prove unreliable and difficult to pin down. The Goat/Rooster will tend to kick out and back away, for he will not accept ties, advice or any form of dependency. His needs for liberty is expressed to a marked degree. He also needs to be reassured and coddled, but dislikes revealing his weakness and takes care not to expose himself.",
      "His principal motivation seems to be to set himself apart from other animals, for his pride will always win out. He wants to be original and fanciful at any price. If you are unlucky enough to come up against these qualities, he will become aggressive and capricious, even a bit cruel. However, he does not hold grudges and the next day you will see him trotting along, eyes shining and flowers for you in hand."
    ],
    "Dog": ["He will be gifted with remarkable intuition. Unfortunately he tends to complicate his life, forever changing his moods, ideas and decisions, constantly retracing his steps and becoming distrustful and pessimistic. However, he will be both faithful and courageous. Even though his nature causes him to constantly put himself in danger, he will never capitulate; he will always see things through to the end. Basically, he needs recognition and devotion; he cannot endure solitude or a lack of affection."],
    "Pig": ["He will not be easy to tame. Of a suspicious nature, the Goat/Pig will seek solitude in thickets and among hidden, rocky paths. In character he is stubborn, obstinate and sometimes even narrow-minded. He is often credulous, but clear-sighted, which is why he prefers to work alone, far from danger and unpleasant encounters. Also, being proud, the Goat/Pig is slow to recognize his errors, but that does not prevent him from being tolerant and always ready to forgive. It is sometimes said that he is a bit of a sorcerer; if you meet up with him, do not forget that at bottom he is tender-hearted and vulnerable."]
  },
  "Monkey": {
    "Rat": ["Before leaving a trip, these two should prepare a first aid kit; their journey is more likely to resemble a hazardous undertaking than an agreeable outing. These two companions believe in the principle of 'an eye for an eye, a tooth for a tooth' and repay each other accordingly. The Monkey will have but one idea: to devour the small rodent. The Rat will use all his tricks, including the most perverse, to make his companion fall into physical, moral and even spiritual traps. These two strange companions will have no tenderness for each other and will give each other no respite. Their journey will become an encounter staged in a prize-fighter's ring, where all blows are allowed and no rules are observe. May the more formidable win!"],
    "Ox": ["The Ox will not resist the Monkey's charm, nor his persuasive and sympathetic magic for very long. Some good advice: if you want peace, give him the illusion that he is stronger but remain attentive and sympathetic. This courageous animal is remarkably agile; physically and mentally he is a first-rate acrobat and gifted with a rare power of persuasion. Take care, for the Monkey is sometimes a sorcerer, capable of transforming all the power of the Ox into mere confetti and mirages."],
    "Tiger": ["Games of hide-and-seek, tricks and hoaxes will blend with feline stratagems and bravery. That sorcerer the Monkey has more than one trick up his sleeve. Depend on him to transform you into a skillful tightrope walker or a dazzling juggler. As playful as the Goat, the game with him is one of getting you to accomplish what he has decided you should accomplish. The Monkey/Tiger is thus a formidable animal which, combining the proud bearing and temperate skills of the Tiger with the ever-present wizardry of the little Monkey, can be counted on to turn anything upside down and provoke many a sleepless night. For the Monkey, leaping unobserved from branch to branch in the jungle with his eyes shut, one cannot aply the usual formula, 'put a Tiger in your tank'. Rather, 'wrap a Tiger within the skin of a mischievous Monkey, and then you will really see something...'"],
    "Rabbit": ["He will be an inventive, lively, rather airy animal. He will have a tendency to be calculating, and will leave nothing to chance. He prefers being a schemer, conjurer and scrounger to labourious and irksome work. The Monkey/Rabbit envisages life as a game which, for the fun of it, he himself strews with traps and mirages, the better to zigzag between them. To attain his ends, he throws scruples to the wind. He will not hesitate to cheat, but who is he deceiving? He does not know himself, unless one day the Sphinx asks him the question."],
    "Dragon": ["Possessing a combination of the supremely gifted synchronized with a talent and taste for walking the tightrope, the Monkey/Dragon - a valiant and fearless guardian - will never unbuckle his armour. Always prepared for war, his days and nights are spent in a state of alertness, much to the continued astonishment of his friends. Alas, he tends to be an extortioner. He has charm, is brilliant and his intelligence is remarkable, but his main defect is his immoderate pride. His company is appreciated, but only in small doses. He will be a phenomenon and his collaboration and assistance will be desired, but you will not be able to breathe freely until you have seen the back of him. So, unwind a little, be natural and glance on your fellow creatures with a less condescending eye."],
    "Snake": ["He will be rational and a good organizer, but he will not be able to conceal his strong superiority complex which, unless he takes care, will cause him major problems. An intelligent and quick animal, his tendency to get carried away will be tempered by deep reflection; even so, he will always refuse to listen to the advice of others, because of his pride and self-esteem. He will not entertain any argument about his ideas, still less that his work or his word be questioned. The Monkey/Snake is talkative, courageous and, at times, a liar. However, his ability and his subtlety are major trump cards."],
    "Horse": ["In turn eloquent and courageous, his path will resemble an extended racecourse, from which the Monkey/Horse can only emerge victorious. He will be as well-balanced as a race horse, at once mount and rider; a Don Juan or a hermit - as well as having a touch of Don Quixote - transforming a track into an arena. He will stake his life - from pride, from a delight in taking risks and even from cynicism. Uniting intelligence with a fine appearance, he exploits to the utmost his resources of charm, talent, wiliness and, sometimes, deceit. The Monkey/Horse will often dream of a path haloed by glory and strewn with flowers - that he will stamp upon with superb indifference."],
    "Goat": ["Intuitive and intelligent, he will be extremely restless. At times pride will curb his fantasies and his ideas will then gain in constancy and consistency, though there is no certainty that he really wants to pursue them to their logical end. The Monkey likes to leap from branch to branch, and the Goat leaps ceaselessly from cloud to cloud. Thus, their alliance will be particularly lively and eventful. As for love, the Monkey/Goat can be a real heartbreaker!"],
    "Monkey": ["He will be by nature chivalrous, slightly boastful and often proud. He will have some difficulties in staying on a straight course; in fact, he will be tempted to take detours and shortcuts for the sheer pleasure of discovery and a taste for novelty. He cannot stay in one place and epitomizes the born traveller. If he comes across an obstacle, he will be tempted to get round it by using guile rather than by overcoming it directly. The Monkey/Monkey will be diabolically intelligent and lucid. However, though luck and happiness are apt to favour him, he will often be incapable of enjoying these gifts; he is too preoccupied with himself and blinded by a narcissism which will rob him of his best opportunities."],
    "Rooster": ["Very proud and full of himself, he will not be, to say the least, modest and self-effacing. He will see to it that he never goes unnoticed and will care a great deal about the effect he produces on others. Lacking neither intelligence nor good taste. he will still be irresistibly attracted by all that glitters. A word of advice: do not call too much attention to his weaknesses because the Monkey/Rooster will never forgive you!"],
    "Dog": ["A supremely intuitive animal, it will be difficult to put him off his trail; he will always find his way despite obstacles and difficulties. However, he has a tendency to complicate his life because to him, everything is a voyage. He hates simplicity, straight lines and mapped-out routes. The Monkey/Dog will often be a character with marked phases of exaltation and depression. Today full of spirit and sure of himself - even a little too much so - tomorrow he will see everything as completely black, questioning his projects, ideas and decisions. Avoid following him if you like to travel in peace."],
    "Pig": ["He will be adept at living in solitude, an extremely clear-sighted person to whom it is inadvisable to talk humbug. In fact, he has a built-in lie detector that sometimes resembles clairvoyance. He has a horror of speaking without purpose. The Monkey/Pig will not be easy to live with: he has his own conceptions of life and will not tolerate having others' imposed on him. He likes to bury his treasures - material or psychological - which are not always of a very clear origin. The Monkey/Pig has, at times, a rather peculiar idea of honesty."]
  },
  "Rooster": {
    "Rat": ["The Rooster, announcing the rising of the sun, and the Rat, busy with his nocturnal activities, are two companions who will hardly have time for sleep. For these two dissimilar characters, a true understanding may seem impossible, yet it is precisely in this that they may prove to be complementary to each other. The Rooster will perch; the Rat will burrow. Each has a lively nature. The one is a sun symbol, the other a symbol of the night. They will mutually strengthen each other. Rat will offer his world of the underground on a gold platter to the Rooster at the very moment when the Rooster, ruffling his feathers, is rising on his spurs awaiting the moment of dawn's song. This is a daily offering on which the Rat would do well to meditate. For Master Rat, so often taking but rarely giving, this generous Rooster will be a source of strength, if he knows how to take what is offered."],
    "Ox": ["The Rooster will add a little wine to his water, or more exactly, he will add a pinch of generosity to his egotism. The Rooster has a sense for sharing and for friendship; admittedly he can behave like a braggart, but then his very ardour and vivacity are so charming that one forgives him everything. From his bravado the Ox will gain a great deal. The morning song of the Rooster will relieve the Ox of a certain torpor and dullness. The ideal would be composed of the Rooster's sharpness on the surface and the Ox's ability in depth."],
    "Tiger": ["He detests banality. His creed is based on the need to be first and to dominate. He is unequalled where the question of pride is concerned; be careful, a voyage is always beset with traps and surprises. The Rooster/Tiger will have a tendency to believe himself to be the winner every time. Alas, the higher he climbs, the greater the fall and, striving always to be first, he will be in danger of running out of breath."],
    "Rabbit": ["He will always keep his eyes peeled. He must always be entitled to the right to look, to control a situation and to feel he is the master of his destiny. He is not the kind to let himself be guided. He is a curious mixture in which the call of the dawn is coupled with the murmurs of the night. The voyage will be profitable if the prudence of the Rabbit is allied with the tenacity and loyalty of the Rooster. The Rooster/Rabbit is a generous, lively animal with a pure heart. His spur and his claw will be used defensively rather than offensively."],
    "Dragon": ["He only feels at ease in a high position, both in the geographic and the hierarchical sense of the term. He prefers the top of a tower or a top floor with terrace. The Rooster/Dragon will always be in the first row and nothing will escape his vigilant gaze; he will wish to dominate, control and supervise in all circumstances. He will be kind and possess originality, qualities which the Rooster does not always naturally cultivate. He will also be irresistibly charming."],
    "Snake": ["An intuitive and frank animal, he will accomplish his tasks with a generous heart and with much good will and honesty - thus correcting the Snake's tendency to side-track - which will not prevent him from being uneasy, despite his apparent self-assurance. The Rooster/Snake flares up easily, so be careful if it is one if his bad days. He will attack with surprising aggressiveness and be entirely unjust simply to reassure himself. Do not attempt to expose his faults with evidence; he will be narrow-minded and never forgive you for having discovered his weak points. The Rooster/Snake is overly concerned with projecting a good image. He has a need to shine and surround himself with costly and beautiful things; this may appear superficial, but it is vital for his morale."],
    "Horse": ["While distinguished, loyal and generous, he is also vain and lacks modesty. His pride drives him, pushing him on against wind and tide, keeping him far in front of the masses, whom he needs to command and carry with him. The Rooster/Horse likes to stand out from the crowd; he is often unique and possesses a sense of honour to the highest degree; his word is his bond. His generosity can be total, his loyalty irreversible. If he gives you his confidence and friendship, nothing - no pressure nor catastrophe - will weaken it."],
    "Goat": [
      "Generous and outgoing, this animal will be honest and pure, but, alas, his character will often prove unreliable and difficult to pin down. The Rooster/Goat will tend to kick out and back away, for he will not accept ties, advice or any form of dependency. His needs for liberty is expressed to a marked degree. He also needs to be reassured and coddled, but dislikes revealing his weakness and takes care not to expose himself.",
      "His principal motivation seems to be to set himself apart from other animals, for his pride will always win out. He wants to be original and fanciful at any price. If you are unlucky enough to come up against these qualities, he will become aggressive and capricious, even a bit cruel. However, he does not hold grudges and the next day you will see him trotting along, eyes shining and flowers for you in hand."
    ],
    "Monkey": ["Very proud and full of himself, he will not be, to say the least, modest and self-effacing. He will see to it that he never goes unnoticed and will care a great deal about the effect he produces on others. Lacking neither intelligence nor good taste. he will still be irresistibly attracted by all that glitters. A word of advice: do not call too much attention to his weaknesses because the Rooster/Monkey will never forgive you!"],
    "Rooster": ["This animal will not pass unnoticed. Others will turn to look at the Rooster/Rooster, who is always dressed in the latest fashion, is rather proud, and tries to stand out among his companions - not because he scorns them, but simply because of his love for originality. He dreams constantly of always being in the forefront, in a high position, at the top of a tree or tower. He is a symbol of vigilance, both protector and look-out. But he will often be aggressive, susceptible, intolerant and rebellious if contradicted. Alert to the external world, he may close up within himself due to his fear of discovering his own weaknesses, as well as those of others."],
    "Dog": ["Imbued with honour and fidelity, the Rooster/Dog will be a sentinel and guardian, yet capable of questioning his handsome self-assurance and looking into himself and tempering his aggressiveness. He will make his way by night as well as day, straddling the two worlds of shade and sun. He will be belligerent, pessimistic and active, but the ordeals he endures will not discourage him. He will persevere, but without any wish for conquest or revenge. The Rooster/Dog will seek to improve himself but remain susceptible to those around him. He will be a man of his word and of his heart."],
    "Pig": ["He is a strange and solitary traveller, due more to personal conviction than to a love of originality. The Rooster/Pig seeks to stand out in a crowd by his attitude towards life rather than by appearance. In order to achieve this, he will seek a hiding place in which to bury his treasures, far from the eyes of the world. He will work hard to acquire wealth and knowledge, but will take care to disguise them so as to be the only one to enjoy them - an expression of his pride and egotism."]
  },
  "Dog": {
    "Rat": [
      "He can be the ideal Companion for the Rat. The Dog is the guide for souls during their 'voyages' and is the guardian of the beyond. Like the rodent, he moves between subterranean and invisible worlds. He is, moreover, a faithful and mysterious Companion, slightly pessimistic for, symbolically, he is often associated with the idea of death. Since the Rat shares this association, the Dog's presence is not always welcome.",
      "Perhaps one day the Rat will try to kill the Dog within him and, in battling against this guardian of the gates, he will break through his constraints. The Companion is sometimes a victim who must be sacrificed during the voyage."
    ],
    "Ox": ["Here is an amalgam that is a little special, for the pessimism of the Dog, added to the slowness and austerity of the Ox, may result in an exceptional and somewhat forbidding gravity. The Dog is the ancient guardian of the Underworld, the Ox of the Labyrinth: this combination of Cerberus and Minotaur will be a bit disquieting. Yet the Dog can bring to the Ox a perspective and power of introspection which he often lacks. The Ox, for his part, will alleviate the doubts, the existential qualms and the tortured questions of the Dog. The Dog/Ox will thus obtain both hope and lucidity; he will know himself a little better, which is the beginning of true wisdom."],
    "Tiger": ["He is a double guardian: the one protects from demons and the other protects souls in the next world. He is a virtuous pessimist disguised in the skin of a man-eating Tiger. The Dog/Tiger will be a thoughtful animal, at his ease in the 'invisible' world and prudent in his own territory. Sure of himself, but calm and circumspect, his Dog side brings an awareness of time and distance, an idea of the ephemeral as well as a sense of detachment. The Dog/Tiger knows better than anyone that after this voyage there will be another. He should be careful, however, for his feet are not on the ground and his halo is askew."],
    "Rabbit": ["In this person the Dog element should be recognized as a guide and guardian, a faithful Companion into the invisible world which lies beyond the voyage of life. The egotistical Rabbit will discover that a precious ally lies within him. The Rabbit/Dog is circumspect, sometimes to the point of sickly distrust. While the sun may be shining on him, he will still be thinking only of the darkness to come. This animal is incapable of living in the present and has a tendency to become obsessed with past failures and future difficulties. He will weep for himself, his often imagined ills, and be depressed by the size of his task! In such moods he is incapable of looking at the simple spectacle of life going on around him, let alone enjoying it."],
    "Dragon": ["He is one of those who inspire confidence, and with reason: one can give him one's friendship wholeheartedly and rely on his word. The Dog/Dragon is a loyal, dedicated and faithful animal who appreciates the luck available for him throughout life, not taking it as his due, but as a gift from Providence. The Dog will understand the value of the Dragon sleeping with him; he, in turn, will give to the Dragon a sense of context, humour and an understanding of a subtle world which includes an interior dimension usually incomprehensible to the Dragon. For the Dragon is always on tenterhooks; usually, he cannot pause to reflect, yet alone contemplate or meditate, and has little contact with the invisible and the hereafter."],
    "Snake": ["He has a keen moral sense, is intuitive, but has a tendency to be pessimistic. Life with him can become very complicated. He is the kind to torment himself to excess, announcing the onset of a hurricane at the least rising of the wind, or a deluge after a few drops of rain. Ever on the watch and constantly on guard, he risks playing the role of the persecuted, one of those flayed alive, whose company one does not usually seek. This is a drawback, particularly since the Dog/Snake is courageous, warm and understands the meaning of faithfulness. However, he has a great need of love and reassurance."],
    "Horse": ["Mount and guide, loyal and faithful, he tenaciously makes his way by day and night, prodded by his intuition. Tempering his impatience and his fire and never doubting his abilities, he is still able to question his ideas and actions and thus improve himself. He succeeds in controlling both his pride and his fear of failure, never hesitating to smile at his defects and his weaknesses, yet he remains ardent and passionate. His Dog side allows him to grasp secrets and dimensions that the Horse can reach only rarely and with difficulty - a world of contemplation and self-questioning in which the Horse's ardour is refined and spiritualized."],
    "Goat": ["He will be gifted with remarkable intuition. Unfortunately he tends to complicate his life, forever changing his moods, ideas and decisions, constantly retracing his steps and becoming distrustful and pessimistic. However, he will be both faithful and courageous. Even though his nature causes him to constantly put himself in danger, he will never capitulate; he will always see things through to the end. Basically, he needs recognition and devotion; he cannot endure solitude or a lack of affection."],
    "Monkey": ["A supremely intuitive animal, it will be difficult to put him off his trail; he will always find his way despite obstacles and difficulties. However, he has a tendency to complicate his life because to him, everything is a voyage. He hates simplicity, straight lines and mapped-out routes. The Dog/Monkey will often be a character with marked phases of exaltation and depression. Today full of spirit and sure of himself - even a little too much so - tomorrow he will see everything as completely black, questioning his projects, ideas and decisions. Avoid following him if you like to travel in peace."],
    "Rooster": ["Imbued with honour and fidelity, the Dog/Rooster will be a sentinel and guardian, yet capable of questioning his handsome self-assurance and looking into himself and tempering his aggressiveness. He will make his way by night as well as day, straddling the two worlds of shade and sun. He will be belligerent, pessimistic and active, but the ordeals he endures will not discourage him. He will persevere, but without any wish for conquest or revenge. The Dog/Rooster will seek to improve himself but remain susceptible to those around him. He will be a man of his word and of his heart."],
    "Dog": ["He will make his way with fear in his heart, forever on guard and rearing up at the slightest sound. He will be a pessimist and riddled with anxiety: the only remedy will be communication with people which will oblige him to get out of himself, go beyond himself and finally, to believe in himself. The Dog/Dog cannot abide solitude; he will go well out of his way if, by so doing, he will find companions to surround himself with and cause him to feel loved. For the Dog/Dog, an offer of affection is the equivalent of a stimulant; it acts as a tonic. Love is his motor. Without it, the Dog/Dog crawls along unsure of himself, going so far as to question why he is alive at all."],
    "Pig": ["The Dog/Pig will be capable of adapting to solitude: he will not hesitate to take wooded paths far from the main roads. By doing so, he will gain self-confidence and his natural self-doubt will be less apparent and weigh less on his companions. He is conscious of his individuality and will tend to turn towards the spiritual world, which attracts and fascinates him. Seeking to pass beyond the threshold of which he is guardian, he will also seek to pass that imperceptible frontier which separates the two universes. While generally favoured in social and material success, the Dog/Pig will remain an enigmatic and mysterious animal to his companions."]
  },
  "Pig": {
    "Rat": [
      "On the one hand, the Pig is eager to cultivate the art of solitude. He will avoid the main routes, preferring bushy paths with their odour of humus and a quiet night lying under the stars. On the other hand, a Pig/Rat is a complete materialist. Hoarder and profiteer, he will know how to capitalize not only on money, but on the fruits of his experiences.",
      "The Pig/Rat will know only white or black; for him there are no shades of grey, no half-measures. His route will be scattered with obstructions which he will ruthlessly overcome. Do not count on him to have scuples; he will not know the meaning of the word.",
      "Be careful! The Pig is credulous and this, added to the curiosity of the Rat, will spring a few traps. So, Pig/Rat, before you set forth, lay in your provisions of cheese and acorns."
    ],
    "Ox": [
      "Both the Ox and the Pig are sometimes slightly egotistical recluses. One is the symbol of fertility, the other of abundance. Their voyage will have every chance of material comfort, but there will be complications. With the Ox in charge, you will face the everyday world with a severe and uncompromising appearance; this will conceal your real life of secret corners and cosy beaches - so enjoyable, luxurious and unconstrained, and made even more pleasurable by discreet weekends, private clubs and closed circles.",
      "If the Pig is in charge, then under the facade of a man who enjoys life to the fullest, will lie an indestructible solidity and an unsuspected tenacity which will often make you all the more formidable, especially in business. Some will think they can soften you up by various means; you will appear all smiles, but inside you will remain glacial."
    ],
    "Tiger": ["He will be the symbol of a successful voyage. But then, everything depends on what one calls 'success'. The solitary Pig will lead the Tiger along sombre paths, revealing mysteries and the spiritual world, but he will expect something in return. The Tiger may be a royal lord of the jungle, but the Pig is master of the palace and the symbol of opulence. But what opulence? This unscrupulous hunter will be neither tepid nor moderate; rather, he will be angelic or diabolical. But be careful: those who act like angels sometimes also act like fools."],
    "Rabbit": ["A solitary animal who is slightly disquieting but perfectly organized. There exists an air of mystery about him; one never knows the real truth. Amassing great wealth, he lives in luxurious comfort but without neglecting the cultivation of his mind. Seductive, he is given to good and bad excesses, a distinction he prefers to ignore. If you corner him, he may either slip away or attack - unless he merely gives you a reply that leaves you breathless. This Pig/Rabbit is often master of a palace of mirages constructed on a base of others' gullibility."],
    "Dragon": ["A solitary wanderer, seeking a treasure that perhaps he did not know how to protect. The Pig/Dragon will tend to gain material and spiritual wealth. Alas, it does not suffice simply to possess matter or mind and spirit - they must be given meaning. Do not sleep before your safe, before the gates of your palace or on the threshold of your mysterious grotto. Ask yourself whether the safe, palace or grotto may be empty; in which case, it is up to you to fill them."],
    "Snake": ["While he is peaceful, secretive and sensitive, he is also a bad loser and his motives are questionable. He does not like to lose and prefers solitude to risking failure. It is useless to try to distract him from his normal routine; he is too obstinate and distrustful. However, this does not stop him from being gullible. It is quite possible to 'take him in'; he will then oscillate between aggressiveness and running away, for at bottom he is tolerant but too proud to admit that his adversary may be right. Although he appears indifferent, the Pig/Snake actually loves money for its own sake and adores amassing treasures and booty. Apparently calm, deep within he is boiling. This solitary reptile is not lukewarm: he is a tough person with a tender heart."],
    "Horse": ["Endowed with a broad and clear intelligence, the Pig/Horse is well aware of the pride that eats away at him. He has a tendency to overrate the true value of his possessions and conquests, and to overlook their impermanence. He cannot resist collecting 'treasures' which are, in fact, fakes. Actually, he unconsciously seeks a more worthy treasure which lies within him. His ardour and impulsiveness often give way to doubt and mystery, the latter irresistibly attracting him like the promise of a profound accomplishment."],
    "Goat": ["He will not be easy to tame. Of a suspicious nature, the Pig/Goat will seek solitude in thickets and among hidden, rocky paths. In character he is stubborn, obstinate and sometimes even narrow-minded. He is often credulous, but clear-sighted, which is why he prefers to work alone, far from danger and unpleasant encounters. Also, being proud, the Pig/Goat is slow to recognize his errors, but that does not prevent him from being tolerant and always ready to forgive. It is sometimes said that he is a bit of a sorcerer; if you meet up with him, do not forget that at bottom he is tender-hearted and vulnerable."],
    "Monkey": ["He will be adept at living in solitude, an extremely clear-sighted person to whom it is inadvisable to talk humbug. In fact, he has a built-in lie detector that sometimes resembles clairvoyance. He has a horror of speaking without purpose. The Pig/Monkey will not be easy to live with: he has his own conceptions of life and will not tolerate having others' imposed on him. He likes to bury his treasures - material or psychological - which are not always of a very clear origin. The Pig/Monkey has, at times, a rather peculiar idea of honesty."],
    "Rooster": ["He is a strange and solitary traveller, due more to personal conviction than to a love of originality. The Pig/Rooster seeks to stand out in a crowd by his attitude towards life rather than by appearance. In order to achieve this, he will seek a hiding place in which to bury his treasures, far from the eyes of the world. He will work hard to acquire wealth and knowledge, but will take care to disguise them so as to be the only one to enjoy them - an expression of his pride and egotism."],
    "Dog": ["The Pig/Dog will be capable of adapting to solitude: he will not hesitate to take wooded paths far from the main roads. By doing so, he will gain self-confidence and his natural self-doubt will be less apparent and weigh less on his companions. He is conscious of his individuality and will tend to turn towards the spiritual world, which attracts and fascinates him. Seeking to pass beyond the threshold of which he is guardian, he will also seek to pass that imperceptible frontier which separates the two universes. While generally favoured in social and material success, the Pig/Dog will remain an enigmatic and mysterious animal to his companions."],
    "Pig": ["This is a solitary and unsociable animal who likes to get away from the main by-ways and planned routes; he is an 'original' who dislikes the company of passing animals. He loves to travel on new and unknown paths, seeking out the mysteries of life, taking shelter in the thickets and shrubs while waiting for night to fall before continuing on his way. He is also an attacker; one should not bar his way unless prepared to face a formidable foe. He does not allow himself to be imprisoned by conventions and regulations and will tend to live on the fringes of society. He is instinctive and intuitive, obeying only his own law, staking out his territory and savagely defending it from intruders."]
  }
};

export const getCompanionshipText = (zodiacSign, companionSign) => {
  const getAnimalSign = (sign) => sign.split(' ')[0];

  const animalSign1 = getAnimalSign(zodiacSign);
  const animalSign2 = getAnimalSign(companionSign);

  const text = companionData[animalSign1]?.[animalSign2];
  return text || ["The data for this combination is not available. Please email me at jarek@siedlarz.com"];
};
